version: "3.1"
services:
    docker-app:
        container_name: react_vote_application
        build:
            context: ./
        env_file: 'src/.env'
        volumes:
            - ./src:/app
        ports:
            - "9190:3000"
        networks:
            - default
volumes:
    persistent:
